version: '3.7'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:     
      - /var/run/docker.sock:/tmp/docker.sock:ro
    
  php-web:
    build: ./php_web
    #user: '1000:1000'
    volumes:
      - ./webapp:/var/www/html
    environment:
      - VIRTUAL_HOST=local.test
    depends_on:      
      - pgsql
      - redis
    # ports:
    # - "8081:80"

  pgsql:
    image: postgres:12-alpine
    #container_name: posgre-lab
    environment:
      POSTGRES_DB: posgres
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: lDKyYi1FQnoQr    
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
  redis:
    #container_name: redis-lab
    image: redis:alpine     
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data      
