version: '3.7'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:     
      - /var/run/docker.sock:/tmp/docker.sock:ro
    
  php-web:     
    build: 
      context: ./php_web
      dockerfile: Dockerfile
      args:
        PROXY: ${PROXY}
    volumes:
      - ./webapp:/var/www/html
    environment:
      - VIRTUAL_HOST=${DOMAIN}
    depends_on:      
      - pgsql
      - redis
    # ports:
    # - "8081:80"

  pgsql:
    image: ${POSTGRES_VER}
    #container_name: posgre-lab
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}    
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
  redis:
    container_name: ${REDIS_HOST}
    image: redis:alpine     
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data      
